In [1]:
using Oscar, Polytropes

  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.1


## $n=4$

In [2]:
G4 = complete_dag(4)

Directed graph with 4 nodes and the following edges:
(1, 2)(1, 3)(1, 4)(2, 3)(2, 4)(3, 4)

In [3]:
I4 = toric_ideal(G4)

Ideal generated by
  e12*e24 - e14
  e12*e23 - e13
  e13*e34 - e14
  e23*e34 - e24

In [4]:
GF4 = groebner_fan(I4)

Polyhedral fan in ambient dimension 6

In [5]:
w4 = Polytropes.interior_points_of_cones(GF4)

10-element Vector{RayVector{QQFieldElem}}:
 [-1, 1, 0, -2, 1, -1]
 [0, 4, -4, 0, 0, 4]
 [0, -1, 1, 3, -3, 2]
 [-2, 2, 0, 0, -2, 2]
 [1, -5//2, 3//2, 5//2, -3//2, 0]
 [2, 3//2, -7//2, 3//2, 1//2, 3]
 [3, 1//2, -7//2, -1//2, 7//2, 0]
 [2, -1//2, -3//2, 7//2, -3//2, 3]
 [1, -3//2, 1//2, -1//2, 3//2, -2]
 [1, 3, -4, -2, 3, 1]

In [10]:
Q4 = weighted_digraph_polyhedron.(Ref(G4), w4)

10-element Vector{Polyhedron{QQFieldElem}}:
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3
 Polyhedron in ambient dimension 3

In [11]:
f_vector.(Q4)

10-element Vector{Vector{ZZRingElem}}:
 [1, 3, 3]
 [4, 8, 5]
 [3, 7, 5]
 [2, 5, 4]
 [3, 7, 5]
 [5, 10, 6]
 [4, 8, 5]
 [5, 10, 6]
 [2, 5, 4]
 [3, 6, 4]

In [8]:
ow4 = weight_ordering.((v->Int.(v.//gcd(v))).(w4), Ref(base_ring(I4) |> default_ordering))

10-element Vector{MonomialOrdering{QQMPolyRing}}:
 matrix_ordering([e12, e13, e14, e23, e24, e34], [-1 1 0 -2 1 -1])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [0 1 -1 0 0 1])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [0 -1 1 3 -3 2])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [-1 1 0 0 -1 1])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [2 -5 3 5 -3 0])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [4 3 -7 3 1 6])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [6 1 -7 -1 7 0])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [4 -1 -3 7 -3 6])*degrevlex([e12, e13, e14, e23, e24, e34])
 matrix_ordering([e12, e13, e14, e23, e24, e34], [2 -3 1 -1 3 -4])*degrevlex([e12, e13

In [9]:
GB4 = map(ow4) do o
    standard_basis(I4; ordering=o)
end

10-element Vector{Oscar.IdealGens{QQMPolyRingElem}}:
 Standard basis with elements
1 -> e13 - e12*e23
2 -> e14 - e12*e23*e34
3 -> e24 - e23*e34
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [-1 1 0 -2 1 -1])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 -> e23*e34 - e24
2 -> e12*e24 - e14
3 -> e13 - e12*e23
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [0 1 -1 0 0 1])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 -> e12*e23 - e13
2 -> e13*e34 - e14
3 -> e14 - e12*e24
4 -> e23*e34 - e24
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [0 -1 1 3 -3 2])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 -> e23*e34 - e24
2 -> e14 - e12*e24
3 -> e13 - e12*e23
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [-1 1 0 0 -1 1])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 

In [40]:
PGB4 = begin
    PGB = MSet()
    for gb in GB4
        push!.(Ref(PGB), gb)
    end
    map(unique(PGB)) do f
        f/leading_coefficient(f)
    end |> unique
end

7-element Vector{QQMPolyRingElem}:
 e13*e34 - e14
 e12*e24 - e14
 e12*e24 - e13*e34
 -e13*e24 + e14*e23
 e12*e23*e34 - e14
 e12*e23 - e13
 e23*e34 - e24

In [41]:
in_C = map(ow4) do o
    lt = leading_term.(unique(PGB4); ordering=o)
    map(lt) do f
        f/leading_coefficient(f)
    end |> unique
end

10-element Vector{Vector{QQMPolyRingElem}}:
 [e13*e34, e12*e24, e13*e24, e14, e13, e24]
 [e13*e34, e12*e24, e13*e24, e12*e23*e34, e13, e23*e34]
 [e13*e34, e14, e14*e23, e12*e23*e34, e12*e23, e23*e34]
 [e13*e34, e14, e14*e23, e12*e23*e34, e13, e23*e34]
 [e14, e12*e24, e14*e23, e12*e23*e34, e12*e23, e23*e34]
 [e13*e34, e12*e24, e13*e24, e12*e23*e34, e12*e23, e23*e34]
 [e13*e34, e12*e24, e13*e24, e12*e23*e34, e12*e23, e24]
 [e13*e34, e12*e24, e14*e23, e12*e23*e34, e12*e23, e23*e34]
 [e14, e12*e24, e14*e23, e12*e23, e24]
 [e13*e34, e12*e24, e13*e24, e12*e23*e34, e13, e24]

## $n=5$

In [28]:
G5 = complete_dag(5)

Directed graph with 5 nodes and the following edges:
(1, 2)(1, 3)(1, 4)(1, 5)(2, 3)(2, 4)(2, 5)(3, 4)(3, 5)(4, 5)

In [29]:
I5 = toric_ideal(G5)

Ideal generated by
  e12*e25 - e15
  e12*e24 - e14
  e12*e24 - e13*e34
  e13*e35 - e15
  e14*e45 - e15
  e23*e35 - e25
  e23*e34 - e24
  e24*e45 - e25
  e34*e45 - e35

In [31]:
GF5 = groebner_fan(I5)

Polyhedral fan in ambient dimension 10

In [32]:
w5 = Polytropes.interior_points_of_cones(GF5)

211-element Vector{RayVector{QQFieldElem}}:
 [1, 0, -5//2, 3//2, 13//2, -1, -9//2, 15//2, -1, 4]
 [0, -3//2, 5//2, -1, 1, 5, -6, -1, 1//2, 13//2]
 [0, -1//2, 3//2, -1, 2, 4, -6, -3, 9//2, 5//2]
 [0, -3//2, 5//2, -1, 6, 0, -6, -1, 11//2, 3//2]
 [1, 8, -5//2, -13//2, 2, -1, 0, 19//2, 1//2, 6]
 [1, 7, -9//2, -7//2, 1, 2, -2, 17//2, -1//2, 6]
 [2, 8, -11//2, -9//2, 1, 5, -4, 13//2, 5//2, 6]
 [0, 5, -9//2, -1//2, 0, -2, 2, 11//2, -1//2, -1]
 [-2, 2, 2, -2, -1, 4, -5, 0, 1, 6]
 [-2, 2, 1, -1, -1, -2, 1, 4, -3, 3]
 [-2, 3, 1//2, -3//2, 0, -5//2, 1//2, 0, 3, -2]
 [-2, 3, -1//2, -1//2, 0, -7//2, 3//2, 4, -1, 0]
 [1, 8, -1//2, -17//2, 2, 1, -2, 3//2, 17//2, 2]
 ⋮
 [4, 13//6, 1//6, -19//3, 7//3, -13//6, 23//6, 8, -7//2, 6]
 [2, 11//3, -29//6, -5//6, 10//3, 7//3, -11//3, 3//2, 11//2, -1]
 [4, 14//3, -17//6, -35//6, 7//3, -8//3, 13//3, 15//2, -1//2, 2]
 [2, 7, -3, -6, 0, 15//2, -11//2, 5//2, 9//2, 7]
 [1, 8, -5//2, -13//2, 2, 4, -5, 9//2, 11//2, 6]
 [4, 7//6, -41//6, 5//3, 4//3, 25//3, -17//3, 2, 1

In [33]:
Q5 = weighted_digraph_polyhedron.(Ref(G5), w5)

211-element Vector{Polyhedron{QQFieldElem}}:
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 ⋮
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4
 Polyhedron in ambient dimension 4

In [34]:
ow5 = weight_ordering.((v->Int.(v.//gcd(v))).(w5), Ref(base_ring(I5) |> default_ordering))

211-element Vector{MonomialOrdering{QQMPolyRing}}:
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [2 0 -5 3 13 -2 -9 15 -2 8])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45])
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [0 -3 5 -2 2 10 -12 -2 1 13])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45])
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [0 -1 3 -2 4 8 -12 -6 9 5])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45])
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [0 -3 5 -2 12 0 -12 -2 11 3])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45])
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [2 16 -5 -13 4 -2 0 19 1 12])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45])
 matrix_ordering([e12, e13, e14, e15, e23, e24, e25, e34, e35, e45], [2 14 -9 -7 2 4 -4 17 -1 12])*degrevlex([e12, e13, e14, e15, e23, e24, e25, e3

In [35]:
GB5 = map(ow4) do o
    standard_basis(I5; ordering=o)
end

10-element Vector{Oscar.IdealGens{QQMPolyRingElem}}:
 Standard basis with elements
1 -> e13*e34 - e12*e24
2 -> e23*e34 - e24
3 -> e13*e35 - e15
4 -> e13*e24 - e12*e23*e24
5 -> e34*e45 - e35
6 -> e14 - e12*e24
7 -> e25 - e24*e45
8 -> e12*e24*e35 - e15*e34
9 -> e12*e24*e45 - e15
10 -> e13*e15 - e12*e15*e23
11 -> e23*e35 - e25
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [-1 1 0 -2 1 -1])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 -> e13*e34 - e14
2 -> e13*e35 - e15
3 -> e12*e23*e34 - e14
4 -> e13*e14 - e12*e14*e23
5 -> e12*e25 - e15
6 -> e23*e35 - e25
7 -> e34*e45 - e35
8 -> e15 - e14*e45
9 -> e13*e25 - e15*e23
10 -> e24 - e23*e34
with respect to the ordering
matrix_ordering([e12, e13, e14, e23, e24, e34], [0 1 -1 0 0 1])*degrevlex([e12, e13, e14, e23, e24, e34])
 Standard basis with elements
1 -> e14 - e13*e34
2 -> e34*e45 - e35
3 -> e24 - e23*e34
4 -> e25 - e23*e35
5 -> e13*e34 - e12*e23*e34
6 -> e13*e35 - e12*e23*e35
7 -> 

In [36]:
PGB5 = begin
    PGB = MSet()
    for gb in GB5
        push!.(Ref(PGB), gb)
    end
    map(unique(PGB)) do f
        f/leading_coefficient(f)
    end |> unique
end

25-element Vector{QQMPolyRingElem}:
 e24*e45 - e25
 e12*e24 - e14
 e12*e25 - e15
 e12*e23*e24 - e13*e24
 e12*e15*e23 - e13*e15
 e12*e14*e23 - e13*e14
 e12*e24*e45 - e15
 e12*e23*e34 - e13*e34
 e13*e35 - e15
 e14*e45 - e15
 e12*e23*e34 - e14
 -e24*e35 + e25*e34
 e12*e24 - e13*e34
 e34*e45 - e35
 e12*e23*e35 - e13*e35
 e12*e23*e35 - e14*e45
 -e13*e25 + e15*e23
 e12*e24*e35 - e15*e34
 e13*e34 - e14
 e23*e35 - e25
 e23*e34 - e24
 e12*e14*e23 - e13^2*e34
 -e13*e24 + e14*e23
 e13*e35 - e14*e45
 -e13*e25 + e14*e23*e45

In [43]:
in_C = map(ow5) do o
    lt = leading_term.(unique(PGB5); ordering=o)
    map(lt) do f
        f/leading_coefficient(f)
    end |> unique
end

211-element Vector{Vector{QQMPolyRingElem}}:
 [e24*e45, e12*e24, e15, e12*e23*e24, e12*e15*e23, e12*e14*e23, e12*e24*e45, e12*e23*e34, e14*e45, e25*e34, e13*e34, e34*e45, e12*e23*e35, e15*e23, e15*e34, e23*e35, e23*e34, e13^2*e34, e14*e23, e14*e23*e45]
 [e24*e45, e12*e24, e15, e12*e23*e24, e12*e15*e23, e12*e14*e23, e12*e24*e45, e12*e23*e34, e13*e35, e14*e45, e14, e24*e35, e34*e45, e12*e23*e35, e15*e23, e12*e24*e35, e23*e35, e24, e14*e23, e14*e23*e45]
 [e24*e45, e12*e24, e15, e12*e23*e24, e12*e15*e23, e12*e14*e23, e12*e24*e45, e12*e23*e34, e13*e35, e14*e45, e14, e24*e35, e35, e12*e23*e35, e15*e23, e12*e24*e35, e23*e35, e24, e14*e23, e14*e23*e45]
 [e24*e45, e14, e15, e12*e23*e24, e12*e15*e23, e12*e14*e23, e12*e24*e45, e12*e23*e34, e13*e35, e14*e45, e24*e35, e12*e24, e35, e12*e23*e35, e15*e23, e12*e24*e35, e23*e35, e23*e34, e14*e23, e14*e23*e45]
 [e24*e45, e12*e24, e12*e25, e13*e24, e13*e15, e13*e14, e12*e24*e45, e13*e34, e13*e35, e14*e45, e12*e23*e34, e25*e34, e34*e45, e12*e23*e35, e13*e